# Generated by Django 2.2.5 on 2019-09-14 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message2',
            field=models.TextField(default=django.utils.timezone.now, max_length=4000),
            preserve_default=False,
        ),
    ]
