# Generated by Django 2.2.5 on 2019-09-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_post_message2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='message2',
        ),
    ]
